// Map openfootball team names to ISO country codes for flagcdn.com flags.
// flagcdn supports UK subdivisions (gb-eng, gb-sct) which the World Cup needs.

const TEAM_CODE: Record<string, string> = {
  Mexico: "mx",
  "South Africa": "za",
  "South Korea": "kr",
  "Czech Republic": "cz",
  Canada: "ca",
  "Bosnia & Herzegovina": "ba",
  Qatar: "qa",
  Switzerland: "ch",
  Brazil: "br",
  Morocco: "ma",
  Haiti: "ht",
  Scotland: "gb-sct",
  USA: "us",
  Paraguay: "py",
  Australia: "au",
  Turkey: "tr",
  Germany: "de",
  "Curaçao": "cw",
  Curacao: "cw",
  "Ivory Coast": "ci",
  Ecuador: "ec",
  Netherlands: "nl",
  Japan: "jp",
  Sweden: "se",
  Tunisia: "tn",
  Belgium: "be",
  Egypt: "eg",
  Iran: "ir",
  "New Zealand": "nz",
  Spain: "es",
  "Cape Verde": "cv",
  "Saudi Arabia": "sa",
  Uruguay: "uy",
  France: "fr",
  Senegal: "sn",
  Iraq: "iq",
  Norway: "no",
  Argentina: "ar",
  Algeria: "dz",
  Austria: "at",
  Jordan: "jo",
  Portugal: "pt",
  "DR Congo": "cd",
  Uzbekistan: "uz",
  Colombia: "co",
  England: "gb-eng",
  Croatia: "hr",
  Ghana: "gh",
  Panama: "pa",
};

/** Flag image URL for a team, or null if we don't have a code (caller shows ⚽). */
export function flagUrl(team: string): string | null {
  const code = TEAM_CODE[team];
  return code ? `https://flagcdn.com/h40/${code}.png` : null;
}

// FIFA Men's World Ranking (June 2026) for the 48 qualified teams.
// Source: FIFA/Coca-Cola Men's World Ranking, June 2026.
const TEAM_RANK: Record<string, number> = {
  France: 1,
  Spain: 2,
  Argentina: 3,
  England: 4,
  Portugal: 5,
  Brazil: 6,
  Netherlands: 7,
  Morocco: 8,
  Belgium: 9,
  Germany: 10,
  Croatia: 11,
  Colombia: 13,
  Senegal: 14,
  Mexico: 15,
  USA: 16,
  Uruguay: 17,
  Japan: 18,
  Switzerland: 19,
  Iran: 21,
  Turkey: 22,
  Ecuador: 23,
  Austria: 24,
  "South Korea": 25,
  Australia: 27,
  Algeria: 28,
  Egypt: 29,
  Canada: 30,
  Norway: 31,
  Panama: 33,
  "Ivory Coast": 34,
  Sweden: 38,
  Paraguay: 40,
  "Czech Republic": 41,
  Scotland: 43,
  Tunisia: 44,
  "DR Congo": 46,
  Uzbekistan: 50,
  Qatar: 55,
  Iraq: 57,
  "South Africa": 60,
  "Saudi Arabia": 61,
  Jordan: 63,
  "Bosnia & Herzegovina": 65,
  "Cape Verde": 69,
  Ghana: 74,
  "Curaçao": 82,
  Haiti: 83,
  "New Zealand": 85,
};

/** FIFA world ranking for a team (lower is better), or undefined if unknown. */
export function teamRank(team: string): number | undefined {
  return TEAM_RANK[team];
}

/** Sort comparator that orders teams by FIFA rank (best first). */
export function byFifaRank(a: string, b: string): number {
  return (TEAM_RANK[a] ?? 999) - (TEAM_RANK[b] ?? 999);
}

// A signature color per nation (kit / flag primary) used as a small accent.
const TEAM_COLOR: Record<string, string> = {
  Mexico: "#006847",
  "South Africa": "#007749",
  "South Korea": "#CD2E3A",
  "Czech Republic": "#11457E",
  Canada: "#FF0000",
  "Bosnia & Herzegovina": "#002F6C",
  Qatar: "#8A1538",
  Switzerland: "#D52B1E",
  Brazil: "#FFDF00",
  Morocco: "#C1272D",
  Haiti: "#00209F",
  Scotland: "#0065BF",
  USA: "#0A3161",
  Paraguay: "#D52B1E",
  Australia: "#FFCD00",
  Turkey: "#E30A17",
  Germany: "#1A1A1A",
  "Curaçao": "#002B7F",
  "Ivory Coast": "#FF8200",
  Ecuador: "#FFD100",
  Netherlands: "#FF6C00",
  Japan: "#0033A0",
  Sweden: "#FECC02",
  Tunisia: "#E70013",
  Belgium: "#E30613",
  Egypt: "#CE1126",
  Iran: "#239F40",
  "New Zealand": "#1A1A1A",
  Spain: "#C60B1E",
  "Cape Verde": "#003893",
  "Saudi Arabia": "#006C35",
  Uruguay: "#5CB8E4",
  France: "#002654",
  Senegal: "#00853F",
  Iraq: "#007A3D",
  Norway: "#BA0C2F",
  Argentina: "#75AADB",
  Algeria: "#006233",
  Austria: "#ED2939",
  Jordan: "#007A3D",
  Portugal: "#C8102E",
  "DR Congo": "#007FFF",
  Uzbekistan: "#0099B5",
  Colombia: "#FCD116",
  England: "#CE1124",
  Croatia: "#FF0000",
  Ghana: "#006B3F",
  Panama: "#005293",
};

/** A team's signature accent color, or a neutral grey if unknown. */
export function teamColor(team: string): string {
  return TEAM_COLOR[team] ?? "#94a3b8";
}
